#!/system/bin/sh
if [ -f "/system/bin/app_process64" ]; then
    mount -o rw,remount /system
    rm -f /system/bin/app_process64_original;
    rm -f /system/bin/app_process_init;
    mv /system/bin/app_process64 /system/bin/app_process64_original;
    ln -sf /system/xbin/daemonsu /system/bin/app_process64;
    cp /system/bin/app_process64_original /system/bin/app_process_init;
    chmod 0755 /system/bin/app_process_init;
    mount -o ro,remount /system
fi